# Generated by Django 3.1.3 on 2020-12-06 22:39

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('address', models.CharField(default='', max_length=150)),
                ('status', models.CharField(choices=[('C', 'Confirmed'), ('AC', 'Awaiting confirmation'), ('DC', 'Declined confimation'), ('B', 'Banned')], default='AC', max_length=2)),
                ('businessNum', models.IntegerField(unique=True)),
                ('phone', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('E', 'Electronics'), ('FS', 'Food Stuff'), ('T', 'Tools')], max_length=3)),
                ('ranking', models.IntegerField(default=0)),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
