# Generated by Django 3.1.3 on 2020-12-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='store',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='logo_img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='store',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(default='Store Address', max_length=150),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(default='Store Name', max_length=150),
        ),
    ]
