# Generated by Django 3.1.3 on 2020-12-09 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_auto_20201208_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='logo_img',
        ),
    ]
