# Generated by Django 3.1.3 on 2020-12-30 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_auto_20201216_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=300, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Store name must be alphanumeric, contain non-exotic symbols (@!#$ and so on) or contain numbers', regex='^[A-Za-z0-9!@#$%^&* ]*$')]),
        ),
    ]
