# Generated by Django 3.1.3 on 2020-12-16 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='form',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], default='O', max_length=2),
        ),
    ]
