# Generated by Django 3.1.3 on 2020-12-16 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0002_auto_20201216_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='data_created',
            new_name='date_created',
        ),
    ]
