# Generated by Django 3.1.3 on 2020-12-16 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Basic', '0004_auto_20201216_2205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='text',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='full_name',
            new_name='name',
        ),
    ]
