# Generated by Django 3.1.3 on 2020-12-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditem',
            name='status',
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='buyer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='ordereditem',
            name='seller',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
