# Generated by Django 3.1.3 on 2020-12-27 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20201227_1954'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ordereditem',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='ordereditem',
            old_name='seller_id',
            new_name='shop_id',
        ),
    ]
