# Generated by Django 3.1.3 on 2021-01-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20201227_2139'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='shop_name',
            field=models.CharField(default='Product name here', max_length=100),
        ),
    ]
