# Generated by Django 3.1.3 on 2021-01-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_ordereditem_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditem',
            name='buyer_name',
            field=models.CharField(default='Buyer name here', max_length=100),
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='product_name',
            field=models.CharField(default='Product name here', max_length=100),
        ),
        migrations.AddField(
            model_name='ordereditem',
            name='shop_name',
            field=models.CharField(default='Store name here', max_length=100),
        ),
    ]
