# Generated by Django 3.1.3 on 2021-01-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_ordereditem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordereditem',
            name='status',
            field=models.CharField(default='Awaiting Shipping', max_length=100),
        ),
    ]
