# Generated by Django 3.1.3 on 2021-01-02 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20210102_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordereditem',
            name='status',
        ),
    ]
