# Generated by Django 3.1.3 on 2020-12-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('Electronics', 'Electronics'), ('Food Stuff', 'Food Stuff'), ('Tools', 'Tools'), ('Other', 'Other')], max_length=222),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default='Description name here', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
