# Generated by Django 3.1.3 on 2020-12-30 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_regulation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Regulation',
        ),
    ]
